import { getGame } from '../core/store.js';
import { localDateString } from '../core/date.js';
import { dungeonSnapshot } from '../dungeon/dungeon-service.js';
import { dungeonFighterSceneHTML, applySceneLayout } from '../visual/scene-renderer.js';
import { BattleEngine } from '../battle/battle-engine.js';
import { openBattle } from '../battle/battle-ui.js';
export function renderDungeon(root,rerender=()=>{}){
  const g=getGame(),snap=dungeonSnapshot(),world=snap.world;if(snap.celebration){root.innerHTML=`<div class="card" style="text-align:center"><div style="font-size:46px">🎊🏰🎊</div><h2>${world?.map||'皇都凱旋遊行'}</h2><div class="small">本週為凱旋週，沒有每日副本戰鬥。</div></div>`;return}
  const e=snap.encounter,ready=snap.heroPower>=snap.enemyPower;root.innerHTML=`<h2>⚔️ 今日副本</h2><div class="card"><div class="world-line"><span class="world-chip">第 ${world.week} 週</span><span class="world-chip">${world.map}</span><span class="world-chip">${localDateString()}</span></div><div class="dungeon-stage"><div class="fighter-card" data-scene="dungeonEntry">${dungeonFighterSceneHTML({side:'hero'})}<div class="fighter-info"><div class="fighter-name">${g.hero.name||'勇者'}</div><div class="power-number good">${snap.heroPower}</div></div></div><div class="vs">VS</div><div class="fighter-card" data-scene="dungeonEntry">${dungeonFighterSceneHTML({side:'enemy',monsterId:e.monsterId})}<div class="fighter-info"><div class="fighter-name">${e.name}</div><div class="power-number bad">${snap.enemyPower}</div></div></div></div><div class="battle-message ${ready?'good':'warn'}">${ready?'⚔️ 可以打！':'💪 再變強一點！'}</div><div class="small">今日平衡：A ${snap.balance.baseCombatPower.toFixed(1)} → B ${snap.balance.maximumTaskPower.toFixed(1)}｜${Math.round(snap.balance.balancePosition*100)}% 位置 → 怪物 ${snap.enemyPower}</div><button id="startBattleV2" class="action-button red" style="width:100%;margin-top:10px">挑戰！</button></div>`;applySceneLayout(root);root.querySelector('#startBattleV2').onclick=()=>openBattle(new BattleEngine({hero:g.hero,monsterId:e.monsterId,enemyPower:snap.enemyPower,eventType:'daily'}),rerender);
}
