import { getFamily, getGame, getState, resetV2 as resetStore } from '../core/store.js';
import { saveSemesterSettings, addExamSubject, removeExamSubject, addTimetableEntry, removeTimetableEntry } from '../gm/semester-admin-service.js';
import { saveTaskDefinition, removeTaskDefinition, toggleTaskDateCancellation, pendingTaskReviews, reviewPendingTask } from '../gm/task-admin-service.js';
import { saveCalendarEvent, deleteCalendarEvent } from '../gm/calendar-admin-service.js';
import { hasParentPin, isParentUnlocked, setParentPin, unlockParent, lockParent, changeParentPin } from '../gm/parent-access-service.js';
import { localDateString } from '../core/date.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sel=(a,b)=>String(a)===String(b)?'selected':'';
const chk=v=>v?'checked':'';
const WEEK=['日','一','二','三','四','五','六'];
let activeTab=sessionStorage.getItem('StudyRPG2_GM_TAB')||'semester',editingTaskId='',editingCalendarId='';
const TABS={semester:'📚 學期與課表',tasks:'📝 任務與核定',calendar:'📅 行事曆',system:'⚙️ 系統'};
function notify(r){if(r?.message)alert(r.message);return !!r?.ok}
function tabNav(){return`<div class="gm-tabs">${Object.entries(TABS).map(([id,label])=>`<button class="gm-tab-btn ${activeTab===id?'active':''}" data-gm-tab="${id}">${label}</button>`).join('')}</div>`}
function weekdayChecks(selected=[]){return[1,2,3,4,5,6,0].map(d=>`<label class="check-chip"><input type="checkbox" data-school-day value="${d}" ${selected.includes(d)?'checked':''}>${WEEK[d]}</label>`).join('')}
function recurringChecks(selected=[]){return[1,2,3,4,5,6,0].map(d=>`<label class="check-chip"><input type="checkbox" data-task-weekday value="${d}" ${selected.includes(d)?'checked':''}>${WEEK[d]}</label>`).join('')}
function subjectOptions(subjects,value=''){return`<option value="">未指定</option>${subjects.map(s=>`<option value="${esc(s.id)}" ${sel(s.id,value)}>${esc(s.name)}</option>`).join('')}`}
function statOptions(value='',allowNone=false){const rows=[['str','力量'],['agi','敏捷'],['int','智力'],['will','意志'],['virtue','美德']];return`${allowNone?`<option value="">無</option>`:''}${rows.map(([id,n])=>`<option value="${id}" ${sel(id,value)}>${n}</option>`).join('')}`}
function categoryOptions(value){const rows=[['study','學習'],['exam_paper','考卷'],['school_reading','學校閱讀'],['extra_reading','額外閱讀'],['sport','運動'],['music','音樂'],['chore','家事'],['selfcare','自理'],['custom','其他']];return rows.map(([id,n])=>`<option value="${id}" ${sel(id,value)}>${n}</option>`).join('')}

function pinSetupHTML(){return`<div class="parent-lock card"><div class="lock-icon">🔐</div><h2>設定家長密碼</h2><div class="small">家長後台會儲存在 2.0 本機資料中；1.0 原始存檔不會被覆寫。</div><input id="gmNewPin" type="password" inputmode="numeric" placeholder="至少 4 位"><input id="gmNewPin2" type="password" inputmode="numeric" placeholder="再輸入一次"><button id="gmSetPin" class="action-button primary">設定並進入</button></div>`}
function lockHTML(){return`<div class="parent-lock card"><div class="lock-icon">🔐</div><h2>家長專區</h2><input id="gmPin" type="password" inputmode="numeric" placeholder="••••"><button id="gmUnlock" class="action-button primary">解鎖</button></div>`}

function semesterPanel(){
  const f=getFamily(),g=getGame(),sem=g.semester||{},rows=(f.schoolTimetable||[]).slice().sort((a,b)=>Number(a.weekday)-Number(b.weekday)||String(a.subjectId).localeCompare(String(b.subjectId)));
  return `<section class="gm-section"><div class="card"><h3>📚 學期基本設定</h3><div class="grid2"><label>學期開始<input id="gmSemStart" type="date" value="${esc(sem.startDate||'')}"></label><label>學期結束<input id="gmSemEnd" type="date" value="${esc(sem.endDate||'')}"></label></div><div class="small">上課日</div><div class="check-row">${weekdayChecks(sem.schoolWeekdays||[1,2,3,4,5])}</div><button id="gmSaveSemester" class="action-button primary">儲存學期設定</button></div>
  <div class="card"><h3>📖 考試科目</h3><div class="simple-list">${(f.examSubjects||[]).map(s=>`<div class="list-row"><span>${esc(s.name)} <small>${esc(s.id)}</small></span><button class="mini-button red" data-remove-subject="${esc(s.id)}">刪除</button></div>`).join('')}</div><div class="row"><input id="gmNewSubject" placeholder="新增科目，例如 自然"><button id="gmAddSubject" class="action-button blue">＋ 科目</button></div></div>
  <div class="card"><h3>🗓️ 每週課表</h3><div class="simple-list">${rows.map(x=>{const sub=(f.examSubjects||[]).find(s=>s.id===x.subjectId);return`<div class="list-row"><span>星期${WEEK[Number(x.weekday)]}｜${esc(sub?.name||x.subjectId)}｜${Number(x.minutes)||40} 分鐘</span><button class="mini-button red" data-remove-timetable="${esc(x.id)}">刪除</button></div>`}).join('')||'<div class="small">目前沒有課表。</div>'}</div><div class="gm-inline-form"><select id="gmTTDay">${[1,2,3,4,5,6,0].map(d=>`<option value="${d}">星期${WEEK[d]}</option>`).join('')}</select><select id="gmTTSubject">${subjectOptions(f.examSubjects)}</select><input id="gmTTMinutes" type="number" min="1" value="40"><button id="gmAddTT" class="action-button blue">加入課表</button></div></div></section>`;
}

function reviewHTML(){const pending=pendingTaskReviews();return`<div class="card"><h3>✅ 任務核定 ${pending.length?`<span class="pill warn">${pending.length}</span>`:''}</h3>${pending.map(r=>{const t=(getGame().tasks||[]).find(x=>String(x.id)===String(r.taskId))||r.taskSnapshot||{};const detail=r.durationMinutes!=null?`耗時 ${Number(r.durationMinutes).toFixed(1)} 分鐘`:r.score!=null?`成績 ${r.score}/${r.scoreMax}`:r.quantity!=null?`${r.quantity} ${r.quantityUnit||'次'}`:'';return`<div class="review-card"><b>${esc(r.date)}｜${esc(t.name||'任務')}</b>${detail?`<div class="small">${esc(detail)}</div>`:''}<div class="review-actions">${[[1,'✅ 100%'],[.8,'🟢 80%'],[.5,'🟡 50%'],[0,'❌ 0%']].map(([v,n])=>`<button class="mini-button ${v===0?'red':''}" data-review="${esc(r.id)}" data-ratio="${v}">${n}</button>`).join('')}</div></div>`}).join('')||'<div class="small">目前沒有待核定任務。</div>'}</div>`}
function taskEditor(){
  const f=getFamily(),g=getGame(),t=editingTaskId?(g.tasks||[]).find(x=>String(x.id)===String(editingTaskId)):null,m=t?.manualStatRewards||{},stat1=t?.fixedStat||Object.keys(m)[0]||'will',stat2=t?.fixedStat2||Object.keys(m).find(k=>k!==stat1)||'',v1=t?.fixedStatValue??m[stat1]??0,v2=t?.fixedStatValue2??m[stat2]??0,start=t?.activeFrom||t?.date||localDateString();
  return `<div class="card" id="gmTaskEditor"><h3>${t?'✏️ 修改任務':'＋ 新增任務'}</h3><label>任務名稱<input id="gmTaskName" value="${esc(t?.name||'')}"></label><div class="grid2"><label>任務類型<select id="gmTaskType"><option value="complete" ${sel(t?.taskType,'complete')}>一般完成</option><option value="timer" ${sel(t?.taskType,'timer')}>計時</option><option value="quantity" ${sel(t?.taskType,'quantity')}>數量</option><option value="score" ${sel(t?.taskType,'score')}>分數</option></select></label><label>分類<select id="gmTaskCategory">${categoryOptions(t?.category||'study')}</select></label><label>難度<select id="gmTaskDifficulty"><option value="easy" ${sel(t?.difficulty,'easy')}>簡單</option><option value="normal" ${sel(t?.difficulty||'normal','normal')}>一般</option><option value="hard" ${sel(t?.difficulty,'hard')}>困難</option><option value="challenge" ${sel(t?.difficulty,'challenge')}>挑戰</option></select></label><label>能力獎勵<select id="gmRewardMode"><option value="auto" ${sel(t?.rewardMode||'auto','auto')}>自動</option><option value="manual" ${sel(t?.rewardMode,'manual')}>手動</option></select></label></div>
  <label>說明<input id="gmTaskDesc" value="${esc(t?.description||'')}"></label><div class="grid2"><label>連結科目<select id="gmTaskSubject">${subjectOptions(f.examSubjects,t?.courseId||'')}</select></label><label>學習進度<input id="gmTaskProgress" value="${esc(t?.progressValue||'')}"></label></div>
  <div class="grid3"><label>金幣<input id="gmTaskGold" type="number" min="0" value="${Number(t?.goldReward)||0}"></label><label>EXP<input id="gmTaskExp" type="number" min="0" value="${Number(t?.expReward)||0}"></label><label>每日上限<input id="gmTaskLimit" type="number" min="1" value="${Math.max(1,Number(t?.dailyLimit)||1)}"></label></div>
  <div class="grid2"><label>日期／開始日期<input id="gmTaskStart" type="date" value="${esc(start)}"></label><label>結束日期<input id="gmTaskEnd" type="date" value="${esc(t?.activeUntil||'')}"></label></div><label class="check-line"><input id="gmTaskRecurring" type="checkbox" ${chk(t?.recurring===true)}> 重複任務</label><div id="gmTaskWeekdays" class="check-row">${recurringChecks(t?.weekdays||[1,2,3,4,5])}</div>
  <div id="gmTimerFields" class="gm-subcard"><b>⏱ 計時設定</b><div class="grid3"><label>模式<select id="gmTimerMode"><option value="deadline" ${sel(t?.timerMode||'deadline','deadline')}>越快越好</option><option value="duration" ${sel(t?.timerMode,'duration')}>累積時間</option></select></label><label>門檻 1<input id="gmFastMinutes" type="number" min="1" value="${Number(t?.fastMinutes)||30}"></label><label>門檻 2<input id="gmStandardMinutes" type="number" min="1" value="${Number(t?.standardMinutes)||60}"></label></div></div>
  <div id="gmQuantityFields" class="gm-subcard"><b>🔢 數量設定</b><div class="grid2"><label>目標<input id="gmQuantityTarget" type="number" min="1" value="${Math.max(1,Number(t?.quantityTarget)||1)}"></label><label>單位<input id="gmQuantityUnit" value="${esc(t?.quantityUnit||'次')}"></label></div></div>
  <div id="gmScoreFields" class="gm-subcard"><b>📝 分數設定</b><label>滿分<input id="gmScoreMax" type="number" min="1" value="${Math.max(1,Number(t?.scoreMax)||100)}"></label></div>
  <div id="gmManualFields" class="gm-subcard"><b>🌱 手動能力獎勵</b><div class="grid2"><label>能力 1<select id="gmStat1">${statOptions(stat1)}</select></label><label>增加<input id="gmStat1Val" type="number" min="0" value="${Number(v1)||0}"></label><label>能力 2<select id="gmStat2">${statOptions(stat2,true)}</select></label><label>增加<input id="gmStat2Val" type="number" min="0" value="${Number(v2)||0}"></label></div></div>
  ${!t?'<label class="check-line"><input id="gmAssignAll" type="checkbox"> 同時指派給所有孩子</label>':''}<div class="row"><button id="gmSaveTask" class="action-button primary">${t?'儲存修改':'新增任務'}</button>${t?'<button id="gmCancelTaskEdit" class="action-button">取消修改</button>':''}</div></div>`;
}
function taskList(){const rows=(getGame().tasks||[]).filter(t=>!t.archived);return`<div class="card"><h3>📋 任務清單</h3>${rows.map(t=>`<div class="list-row task-admin-row"><span><b>${esc(t.name)}</b><small>${t.recurring?'重複':'單次'}｜${esc(t.taskType||'complete')}｜${esc(t.subject||'未指定科目')}</small></span><span class="admin-actions"><button class="mini-button blue" data-edit-task="${esc(t.id)}">修改</button><button class="mini-button" data-cancel-task-date="${esc(t.id)}">取消日期</button><button class="mini-button red" data-remove-task="${esc(t.id)}">刪除／封存</button></span></div>`).join('')||'<div class="small">尚未建立任務。</div>'}</div>`}
function tasksPanel(){return`<section class="gm-section">${reviewHTML()}${taskEditor()}${taskList()}</section>`}

function calendarEditor(){
  const f=getFamily(),e=editingCalendarId?(f.adventureCalendar||[]).find(x=>String(x.id)===String(editingCalendarId)):null,type=e?.type||'general';
  return`<div class="card"><h3>${e?'✏️ 修改事件':'＋ 新增行事曆事件'}</h3><div class="grid2"><label>日期<input id="gmCalDate" type="date" value="${esc(e?.date||localDateString())}"></label><label>類型<select id="gmCalType"><option value="general" ${sel(type,'general')}>一般</option><option value="activity" ${sel(type,'activity')}>活動</option><option value="holiday" ${sel(type,'holiday')}>放假</option><option value="midterm" ${sel(type,'midterm')}>期中考</option><option value="final" ${sel(type,'final')}>期末考</option><option value="semester_start" ${sel(type,'semester_start')}>學期開始</option><option value="semester_end" ${sel(type,'semester_end')}>學期結束</option></select></label></div><label>事件名稱<input id="gmCalName" value="${esc(e?.name||'')}"></label><label class="check-line"><input id="gmCalAllDay" type="checkbox" ${chk(e?.allDay!==false)}> 全天事件</label><div class="grid2" id="gmCalTimeFields"><label>開始<input id="gmCalStart" type="time" value="${esc(e?.startTime||'')}"></label><label>結束<input id="gmCalEnd" type="time" value="${esc(e?.endTime||'')}"></label></div><label>附註<textarea id="gmCalNote" rows="3">${esc(e?.note||'')}</textarea></label><div class="grid2"><label>提前提醒<select id="gmCalReminder">${[[0,'不提醒'],[10,'10 分鐘'],[30,'30 分鐘'],[60,'1 小時'],[1440,'1 天'],[4320,'3 天'],[10080,'7 天']].map(([v,n])=>`<option value="${v}" ${sel(Number(e?.reminderMinutes||0),v)}>${n}</option>`).join('')}</select></label><label>顯示對象<select id="gmCalTarget"><option value="all" ${sel(e?.targetType||'all','all')}>所有孩子</option><option value="selected" ${sel(e?.targetType,'selected')}>指定孩子</option></select></label></div><div id="gmCalTargets" class="gm-subcard"><b>指定孩子</b>${f.profiles.map(p=>`<label class="check-line"><input type="checkbox" data-cal-target value="${esc(p.id)}" ${chk((e?.targetProfileIds||[]).includes(p.id))}> ${p.data.hero.gender==='female'?'👧':'👦'} ${esc(p.data.hero.name||p.label)}</label>`).join('')}</div><div id="gmCalExamSubjects" class="gm-subcard"><b>考試科目</b>${f.examSubjects.map(s=>`<label class="check-line"><input type="checkbox" data-cal-subject value="${esc(s.id)}" ${chk((e?.examSubjectIds||[]).includes(s.id))}> ${esc(s.name)}</label>`).join('')}</div><label class="check-line"><input id="gmCalRequire" type="checkbox" ${chk(e?.requireComplete===true)}> 需要完成確認</label><div class="row"><button id="gmSaveCalendar" class="action-button primary">${e?'儲存修改':'新增事件'}</button>${e?'<button id="gmCancelCalendarEdit" class="action-button">取消修改</button>':''}</div></div>`;
}
function calendarPanel(){const f=getFamily(),events=(f.adventureCalendar||[]).slice().sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));return`<section class="gm-section">${calendarEditor()}<div class="card"><h3>🗺️ 行事曆事件</h3>${events.map(e=>`<div class="list-row task-admin-row"><span><b>${esc(e.date)}｜${esc(e.name)}</b><small>${esc(e.type)}${e.allDay?'｜全天':e.startTime?`｜${esc(e.startTime)}${e.endTime?'～'+esc(e.endTime):''}`:''}</small></span><span class="admin-actions"><button class="mini-button blue" data-edit-calendar="${esc(e.id)}">修改</button><button class="mini-button red" data-delete-calendar="${esc(e.id)}">刪除</button></span></div>`).join('')||'<div class="small">目前沒有事件。</div>'}</div></section>`}

function systemPanel(){const s=getState();return`<section class="gm-section"><div class="card"><h3>⚙️ 2.0 系統狀態</h3><div class="simple-list"><div class="list-row"><span>資料來源</span><b>${esc(s.source)}</b></div><div class="list-row"><span>目前 schema</span><b>${Number(s.schemaVersion)||2}</b></div><div class="list-row"><span>1.0 存檔</span><b>只讀遷移，不覆寫</b></div><div class="list-row"><span>舊 runtime 暫存</span><b>不再整包帶入 2.0</b></div></div></div><div class="card"><h3>🔑 修改家長密碼</h3><input id="gmOldPin" type="password" placeholder="目前密碼"><input id="gmChangePin1" type="password" placeholder="新密碼"><input id="gmChangePin2" type="password" placeholder="再輸入一次"><div class="row"><button id="gmChangePin" class="action-button blue">修改密碼</button><button id="gmLock" class="action-button">鎖定後台</button></div></div><div class="card"><h3 class="bad">危險操作</h3><button id="gmReset2" class="action-button red">清除 2.0 存檔並重新從 1.0 乾淨遷移</button><div class="small">只移除 <code>StudyRPG2_STATE</code>；不刪除 1.0 原始存檔。</div></div><div class="dev-note">商店交易、抽獎交易、Inventory lifecycle、Firebase Family Provider 仍要等各自正式 Service 完成後再接，不在 GM UI 內先寫第二套規則。</div></section>`}

function syncTaskFields(root){const type=root.querySelector('#gmTaskType')?.value||'complete',manual=root.querySelector('#gmRewardMode')?.value==='manual',recurring=root.querySelector('#gmTaskRecurring')?.checked===true;root.querySelector('#gmTimerFields')?.classList.toggle('hidden',type!=='timer');root.querySelector('#gmQuantityFields')?.classList.toggle('hidden',type!=='quantity');root.querySelector('#gmScoreFields')?.classList.toggle('hidden',type!=='score');root.querySelector('#gmManualFields')?.classList.toggle('hidden',!manual);root.querySelector('#gmTaskWeekdays')?.classList.toggle('hidden',!recurring)}
function syncCalendarFields(root){const type=root.querySelector('#gmCalType')?.value||'general',allDay=root.querySelector('#gmCalAllDay')?.checked!==false,target=root.querySelector('#gmCalTarget')?.value||'all';root.querySelector('#gmCalTimeFields')?.classList.toggle('hidden',allDay);root.querySelector('#gmCalTargets')?.classList.toggle('hidden',target!=='selected');root.querySelector('#gmCalExamSubjects')?.classList.toggle('hidden',!['midterm','final'].includes(type))}

function bindSemester(root){
  root.querySelector('#gmSaveSemester')?.addEventListener('click',()=>notify(saveSemesterSettings({startDate:root.querySelector('#gmSemStart').value,endDate:root.querySelector('#gmSemEnd').value,schoolWeekdays:[...root.querySelectorAll('[data-school-day]:checked')].map(x=>Number(x.value))})));
  root.querySelector('#gmAddSubject')?.addEventListener('click',()=>{if(notify(addExamSubject(root.querySelector('#gmNewSubject').value)))renderGM(root)});
  root.querySelectorAll('[data-remove-subject]').forEach(b=>b.onclick=()=>{if(confirm('刪除這個科目？')&&notify(removeExamSubject(b.dataset.removeSubject)))renderGM(root)});
  root.querySelector('#gmAddTT')?.addEventListener('click',()=>{if(notify(addTimetableEntry({weekday:root.querySelector('#gmTTDay').value,subjectId:root.querySelector('#gmTTSubject').value,minutes:root.querySelector('#gmTTMinutes').value})))renderGM(root)});
  root.querySelectorAll('[data-remove-timetable]').forEach(b=>b.onclick=()=>{if(notify(removeTimetableEntry(b.dataset.removeTimetable)))renderGM(root)});
}
function readTaskForm(root){return{name:root.querySelector('#gmTaskName').value,taskType:root.querySelector('#gmTaskType').value,category:root.querySelector('#gmTaskCategory').value,difficulty:root.querySelector('#gmTaskDifficulty').value,rewardMode:root.querySelector('#gmRewardMode').value,description:root.querySelector('#gmTaskDesc').value,courseId:root.querySelector('#gmTaskSubject').value,progressValue:root.querySelector('#gmTaskProgress').value,goldReward:root.querySelector('#gmTaskGold').value,expReward:root.querySelector('#gmTaskExp').value,dailyLimit:root.querySelector('#gmTaskLimit').value,activeFrom:root.querySelector('#gmTaskStart').value,activeUntil:root.querySelector('#gmTaskEnd').value,recurring:root.querySelector('#gmTaskRecurring').checked,weekdays:[...root.querySelectorAll('[data-task-weekday]:checked')].map(x=>Number(x.value)),timerMode:root.querySelector('#gmTimerMode').value,fastMinutes:root.querySelector('#gmFastMinutes').value,standardMinutes:root.querySelector('#gmStandardMinutes').value,fixedStat:root.querySelector('#gmStat1').value,fixedStatValue:root.querySelector('#gmStat1Val').value,fixedStat2:root.querySelector('#gmStat2').value,fixedStatValue2:root.querySelector('#gmStat2Val').value,quantityTarget:root.querySelector('#gmQuantityTarget').value,quantityUnit:root.querySelector('#gmQuantityUnit').value,scoreMax:root.querySelector('#gmScoreMax').value}}
function bindTasks(root){
  ['#gmTaskType','#gmRewardMode','#gmTaskRecurring'].forEach(q=>root.querySelector(q)?.addEventListener('change',()=>syncTaskFields(root)));syncTaskFields(root);
  root.querySelector('#gmSaveTask')?.addEventListener('click',()=>{const r=saveTaskDefinition(readTaskForm(root),{editingId:editingTaskId,assignAll:!!root.querySelector('#gmAssignAll')?.checked});if(notify(r)){editingTaskId='';renderGM(root)}});
  root.querySelector('#gmCancelTaskEdit')?.addEventListener('click',()=>{editingTaskId='';renderGM(root)});
  root.querySelectorAll('[data-edit-task]').forEach(b=>b.onclick=()=>{editingTaskId=b.dataset.editTask;renderGM(root);root.querySelector('#gmTaskEditor')?.scrollIntoView({behavior:'smooth'})});
  root.querySelectorAll('[data-remove-task]').forEach(b=>b.onclick=()=>{if(confirm('刪除這個任務？已有歷史紀錄時會改為封存。')&&notify(removeTaskDefinition(b.dataset.removeTask)))renderGM(root)});
  root.querySelectorAll('[data-cancel-task-date]').forEach(b=>b.onclick=()=>{const d=prompt('輸入要取消／恢復的日期（YYYY-MM-DD）',localDateString());if(d&&notify(toggleTaskDateCancellation(b.dataset.cancelTaskDate,d)))renderGM(root)});
  root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{if(notify(reviewPendingTask(b.dataset.review,Number(b.dataset.ratio))))renderGM(root)});
}
function readCalendar(root){return{date:root.querySelector('#gmCalDate').value,type:root.querySelector('#gmCalType').value,name:root.querySelector('#gmCalName').value,allDay:root.querySelector('#gmCalAllDay').checked,startTime:root.querySelector('#gmCalStart').value,endTime:root.querySelector('#gmCalEnd').value,note:root.querySelector('#gmCalNote').value,reminderMinutes:root.querySelector('#gmCalReminder').value,targetType:root.querySelector('#gmCalTarget').value,targetProfileIds:[...root.querySelectorAll('[data-cal-target]:checked')].map(x=>x.value),examSubjectIds:[...root.querySelectorAll('[data-cal-subject]:checked')].map(x=>x.value),requireComplete:root.querySelector('#gmCalRequire').checked}}
function bindCalendar(root){['#gmCalType','#gmCalAllDay','#gmCalTarget'].forEach(q=>root.querySelector(q)?.addEventListener('change',()=>syncCalendarFields(root)));syncCalendarFields(root);root.querySelector('#gmSaveCalendar')?.addEventListener('click',()=>{const r=saveCalendarEvent(readCalendar(root),{editingId:editingCalendarId});if(notify(r)){editingCalendarId='';renderGM(root)}});root.querySelector('#gmCancelCalendarEdit')?.addEventListener('click',()=>{editingCalendarId='';renderGM(root)});root.querySelectorAll('[data-edit-calendar]').forEach(b=>b.onclick=()=>{editingCalendarId=b.dataset.editCalendar;renderGM(root)});root.querySelectorAll('[data-delete-calendar]').forEach(b=>b.onclick=()=>{if(confirm('刪除這個事件？')&&notify(deleteCalendarEvent(b.dataset.deleteCalendar)))renderGM(root)})}
function bindSystem(root,rerender){root.querySelector('#gmLock')?.addEventListener('click',()=>{lockParent();renderGM(root,rerender)});root.querySelector('#gmChangePin')?.addEventListener('click',async()=>notify(await changeParentPin(root.querySelector('#gmOldPin').value,root.querySelector('#gmChangePin1').value,root.querySelector('#gmChangePin2').value)));root.querySelector('#gmReset2')?.addEventListener('click',()=>{if(!confirm('確定清除 2.0 存檔並重新從 1.0 遷移？'))return;resetStore();editingTaskId='';editingCalendarId='';rerender?.()})}

export function renderGM(root,rerender=()=>{}){
  if(!hasParentPin()){
    root.innerHTML=pinSetupHTML();root.querySelector('#gmSetPin').onclick=async()=>{const r=await setParentPin(root.querySelector('#gmNewPin').value,root.querySelector('#gmNewPin2').value);if(notify(r))renderGM(root,rerender)};return;
  }
  if(!isParentUnlocked()){
    root.innerHTML=lockHTML();root.querySelector('#gmUnlock').onclick=async()=>{const r=await unlockParent(root.querySelector('#gmPin').value);if(notify(r))renderGM(root,rerender)};return;
  }
  if(!TABS[activeTab])activeTab='semester';const panel=activeTab==='semester'?semesterPanel():activeTab==='tasks'?tasksPanel():activeTab==='calendar'?calendarPanel():systemPanel();
  root.innerHTML=`<h2>🛠️ 家長控制後台</h2>${tabNav()}${panel}`;
  root.querySelectorAll('[data-gm-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.gmTab;sessionStorage.setItem('StudyRPG2_GM_TAB',activeTab);renderGM(root,rerender)});
  if(activeTab==='semester')bindSemester(root);else if(activeTab==='tasks')bindTasks(root);else if(activeTab==='calendar')bindCalendar(root);else bindSystem(root,rerender);
}
