import { getGame } from '../core/store.js';
import { buyShopItem, drawLottery, requestInventoryUse, shopItemCategory, inventoryGroups, itemDefinition, ITEM_CATEGORY_LABELS, EQUIP_SLOT_LABELS, equipmentStatText, equipInventory, ensureEconomyCatalog } from '../economy/economy-service.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function list(title,rows){return `<h2>${title}</h2><div class="simple-list">${rows.length?rows.map(([a,b])=>`<div class="list-row"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join(''):'<div class="card empty">目前沒有資料。</div>'}</div>`}
function notify(r){if(r?.message)alert(r.message);return !!r?.ok}
function sourceName(s){return s==='dungeon'?'副本掉落':s==='lottery'?'抽獎':s==='gm_backfill'?'家長回補':s==='shop'?'商店':'其他'}
let shopCategoryFilter='all',bagCategoryFilter='all';
function tabs(current,kind){return `<div class="item-tabs">${Object.entries(ITEM_CATEGORY_LABELS).map(([k,v])=>`<button class="${current===k?'active':''}" data-${kind}-cat="${k}">${v}</button>`).join('')}</div>`}
function itemMeta(item){const cat=shopItemCategory(item);if(cat==='equipment')return `<div class="item-meta">${EQUIP_SLOT_LABELS[item.equipSlot]||'裝備'}｜${esc(equipmentStatText(item))}</div>`;if(cat==='consumable'){const t=item.effectType==='heal_hp'?`恢復 ${Number(item.effectValue)||0} HP`:item.effectType==='heal_energy'?`恢復 ${Number(item.effectValue)||0} 能量`:item.effectType==='poison'?`中毒 ${Number(item.effectTurns)||3} 回合`:'戰鬥消耗品';return `<div class="item-meta">${esc(t)}</div>`}return ''}

export function renderShop(root){
  const g=ensureEconomyCatalog(),items=(g.shopItems||[]).filter(x=>x.active!==false&&(shopCategoryFilter==='all'||shopItemCategory(x)===shopCategoryFilter));
  root.innerHTML=`<h2>🏪 商店</h2><div class="card"><b>目前金幣：${Math.max(0,Number(g.hero.gold)||0)} G</b></div>${tabs(shopCategoryFilter,'shop')}${items.map(i=>`<div class="card"><strong>${esc(i.icon||'🎁')} ${esc(i.name)}</strong> <span class="pill">${esc(ITEM_CATEGORY_LABELS[shopItemCategory(i)]||shopItemCategory(i))}</span><div class="small">${esc(i.description||'')}</div>${itemMeta(i)}<div>價格：<span class="bad">${Math.max(0,Number(i.price)||0)} G</span>｜每日限購 ${Math.max(1,Number(i.dailyLimit)||1)}</div><button class="action-button blue" data-buy-shop="${esc(i.id)}">購買</button></div>`).join('')||'<div class="card empty">這個分類目前沒有商品。</div>'}`;
  root.querySelectorAll('[data-shop-cat]').forEach(b=>b.onclick=()=>{shopCategoryFilter=b.dataset.shopCat;renderShop(root)});
  root.querySelectorAll('[data-buy-shop]').forEach(b=>b.onclick=()=>{const item=items.find(x=>String(x.id)===String(b.dataset.buyShop));if(!item||!confirm(`花費 ${Math.max(0,Number(item.price)||0)} G 購買【${item.name}】？`))return;notify(buyShopItem(item.id))});
}

export function renderLottery(root){
  const g=ensureEconomyCatalog(),pool=(g.lotteryPool||[]).filter(x=>x.active!==false);
  root.innerHTML=`<h2>🎰 勇者抽獎機</h2><div class="card"><div>目前抽獎金幣：<strong class="purple">${Math.max(0,Number(g.hero.lotteryCoins)||0)}</strong> 🪙</div><div class="small">每次消耗 1 枚抽獎金幣；抽中獎項會進背包，依兌換券流程由家長核准。</div><button id="drawLotteryV2" class="action-button purple" style="margin-top:10px" ${(Number(g.hero.lotteryCoins)||0)<1?'disabled':''}>抽獎一次</button></div><div class="card"><h3>目前獎池</h3>${pool.map(x=>`<div class="small">${esc(x.label||x.name)}｜權重 ${Number(x.weight)||0}｜${x.unlimited===true||((x.unlimited==null)&&Number(x.stock)===0)?'不限次數':'剩 '+Math.max(0,Number(x.stock)||0)}</div>`).join('')||'<div class="small">目前沒有獎項。</div>'}</div>`;
  root.querySelector('#drawLotteryV2')?.addEventListener('click',()=>notify(drawLottery()));
}

function equipmentPanel(g){return `<div class="card"><h3>🛡️ 裝備欄</h3><div class="equipment-grid">${Object.entries(EQUIP_SLOT_LABELS).map(([slot,label])=>{const id=g.hero?.equipment?.[slot],inv=(g.inventory||[]).find(x=>String(x.id)===String(id)),item=itemDefinition(inv,g);return `<div class="equip-slot"><strong>${label}</strong>${inv?`<span>${esc(item?.icon||'🛡️')} ${esc(inv.name)}</span><div class="item-meta">${esc(equipmentStatText(item||inv))}</div><button class="mini-button" data-equip="${esc(inv.id)}">卸下</button>`:'<span class="small">未裝備</span>'}</div>`}).join('')}</div></div>`}

export function renderBag(root){
  const g=ensureEconomyCatalog(),active=(g.inventory||[]).filter(inv=>inv.status!=='used'&&(bagCategoryFilter==='all'||shopItemCategory(inv)===bagCategoryFilter)),used=(g.inventory||[]).filter(inv=>inv.status==='used'&&shopItemCategory(inv)==='coupon'&&(bagCategoryFilter==='all'||bagCategoryFilter==='coupon'));
  const groups=inventoryGroups(active,g);
  root.innerHTML=`<h2>🎒 背包</h2>${equipmentPanel(g)}${tabs(bagCategoryFilter,'bag')}${groups.map(group=>{const inv=group.inv,item=itemDefinition(inv,g)||inv,cat=group.category,equipped=cat==='equipment'&&Object.values(g.hero?.equipment||{}).some(id=>String(id)===String(inv.id)),stackable=['coupon','consumable'].includes(cat),count=stackable&&group.count>1?` <span class="pill good">×${group.count}</span>`:'',pending=group.pendingCount?`<div class="small warn">等待家長核准：${group.pendingCount}</div>`:'',src=group.sources.length>1?'多重來源':sourceName(group.sources[0]);let action='';if(cat==='equipment')action=`<button class="action-button ${equipped?'':'blue'}" data-equip="${esc(inv.id)}">${equipped?'卸下':'裝備'}</button>`;else if(cat==='consumable')action='<div class="small good">⚔️ 戰鬥消耗品：在戰鬥的「道具」中使用。</div>';else if(group.unusedCount>0)action=`<button class="action-button gold" data-request-use="${esc(group.instances.find(x=>x.status==='unused')?.id||inv.id)}">申請使用 1 ${cat==='coupon'?'張':'個'}</button>`;return `<div class="card"><strong>${esc(item?.icon||'📦')} ${esc(inv.name||inv.itemId||'物品')}</strong>${count} <span class="pill">${esc(ITEM_CATEGORY_LABELS[cat]||cat)}</span><div class="small">來源：${esc(src)}</div>${pending}${itemMeta(item)}${action}</div>`}).join('')||'<div class="card small">這個分類目前沒有可使用的物品。</div>'}${used.length?`<details class="card"><summary style="cursor:pointer;font-weight:900">🧾 已使用兌換券紀錄（${used.length}）</summary>${used.slice().sort((a,b)=>String(b.usedDate||b.boughtDate||'').localeCompare(String(a.usedDate||a.boughtDate||''))).map(inv=>{const req=(g.couponRequests||[]).find(r=>String(r.id)===String(inv.usedRequestId))||(g.couponRequests||[]).find(r=>String(r.inventoryId)===String(inv.id)&&r.status==='approved');return `<div class="list-row"><span><b>${esc(inv.name||'兌換品')}</b><small>${esc(req?.itemName||'')}</small></span><b>${esc(inv.usedDate||req?.approvedDate||req?.date||'未記錄')}</b></div>`}).join('')}</details>`:''}`;
  root.querySelectorAll('[data-bag-cat]').forEach(b=>b.onclick=()=>{bagCategoryFilter=b.dataset.bagCat;renderBag(root)});
  root.querySelectorAll('[data-request-use]').forEach(b=>b.onclick=()=>notify(requestInventoryUse(b.dataset.requestUse)));
  root.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>notify(equipInventory(b.dataset.equip)));
}

export function renderSocial(root){const g=getGame(),s=g.social||{};root.innerHTML=`<h2>🤝 好友與線上冒險</h2><div class="grid3"><div class="card"><h3>👥 好友</h3><b>${(s.friends||[]).length}</b></div><div class="card"><h3>⚔️ PVP</h3><div class="small">Provider 未接入</div></div><div class="card"><h3>✉️ 信箱</h3><b>${(s.inbox||[]).length}</b></div></div>`}
