import { BATTLE_CONFIG } from './battle-config.js';
import { makeHeroBattleStats, deriveEnemyStats, resolveAttack, addStatus, effectMod, effectiveBattleValue, statusLabel } from './battle-math.js';
import { monsterDef } from './monster-database.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function actionSummary(r,target){if(r.type==='miss')return'💨 攻擊落空！';if(r.type==='dodge')return`💨 ${target}閃避成功！`;if(r.type==='parry')return`⚔️ ${target}招架成功！`;if(r.type==='block')return`🛡️ ${target}格擋，只受到 ${r.damage} 點傷害。`;return`${r.crit?'💥 致命一擊！':''}${r.weak?' WEAK！':''}${r.resisted?' RESIST！':''}造成 ${r.damage} 點傷害。`}
function modifiersToMap(modifiers=[]){const out={};for(const m of modifiers){if(m?.operation==='add')out[m.target]=(out[m.target]||0)+Number(m.value||0)}return out}
export class BattleEngine{
 constructor({hero,monsterId,enemyPower,eventType='daily'}={}){this.heroSource=hero;this.monsterId=monsterId;this.enemyPower=Number(enemyPower)||1;this.eventType=eventType;this.listeners=new Set();this.state=null}
 subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}
 emit(event){for(const fn of this.listeners)fn(this.snapshot(),event)}
 snapshot(){return this.state?structuredClone(this.state):null}
 start(){const hero=makeHeroBattleStats(this.heroSource),def=monsterDef(this.monsterId),base=def.mirrorHero?makeHeroBattleStats(this.heroSource):deriveEnemyStats(this.enemyPower,def,this.eventType),scale=def.finalBoss?1.35:1,enemy={...base,uid:`${def.id}_${Date.now().toString(36)}`,monsterId:def.id,name:def.name,isBoss:def.boss||['midterm','final'].includes(this.eventType),isSummon:false,maxHp:Math.max(1,Math.round(base.maxHp*scale)),hp:0,alive:true,statuses:[],skillUses:{},cooldowns:{}};enemy.hp=enemy.maxHp;this.state={hero,enemies:[enemy],selectedEnemyUid:enemy.uid,round:0,busy:false,ended:false,result:'',heroHp:hero.maxHp,heroEnergy:Math.round(hero.maxEnergy*.50),logs:['⚔️ 戰鬥開始！先鎖定目標再選擇行動。'],enemyPower:this.enemyPower,eventType:this.eventType,monsterId:this.monsterId};this.emit({type:'start'});return this.snapshot()}
 target(){const s=this.state;if(!s)return null;const alive=s.enemies.filter(x=>x.alive!==false&&x.hp>0);let t=alive.find(x=>x.uid===s.selectedEnemyUid)||alive[0]||null;if(t)s.selectedEnemyUid=t.uid;return t}
 log(message){this.state.logs.push(message);if(this.state.logs.length>16)this.state.logs.shift();this.emit({type:'log',message})}
 selectTarget(uid){if(!this.state||this.state.busy||this.state.ended)return false;const t=this.state.enemies.find(x=>x.uid===uid&&x.hp>0&&x.alive!==false);if(!t)return false;this.state.selectedEnemyUid=uid;this.log(`🎯 鎖定目標：${t.name}`);return true}
 async present(presenter,event){this.emit(event);if(presenter)await presenter(event,this.snapshot())}
 statusTick(unit,isHero=false){let skip=false;for(const st of [...(unit.statuses||[])]){let dmg=0;if(['poison','burn','bleed'].includes(st.type))dmg=Math.max(1,Math.round(st.power||5));if(dmg){if(isHero)this.state.heroHp=Math.max(0,this.state.heroHp-dmg);else{unit.hp=Math.max(0,unit.hp-dmg);unit.alive=unit.hp>0}this.log(`${statusLabel(st)}：${unit.name}受到 ${dmg} 點傷害。`)}if(['stun','paralysis','freeze'].includes(st.type)&&st.guaranteedSkip!==false)skip=true;st.turns--}unit.statuses=(unit.statuses||[]).filter(s=>s.turns>0);return skip}
 initiative(){const rows=[{side:'hero',unit:this.state.hero,order:0},...this.state.enemies.filter(x=>x.hp>0&&x.alive!==false).map((unit,i)=>({side:'enemy',unit,order:i+1}))];return rows.sort((a,b)=>effectiveBattleValue(b.unit,'speed')-effectiveBattleValue(a.unit,'speed')||a.order-b.order)}
 async executeDamage(attacker,defender,action,presenter,side){const result=resolveAttack(attacker,defender,action);await this.present(presenter,{type:'attack',side,result,action,attackerName:attacker.name,targetName:defender.name,targetUid:defender.uid||'hero'});if(result.damage){if(side==='hero'){defender.hp=Math.max(0,defender.hp-result.damage);defender.alive=defender.hp>0}else this.state.heroHp=Math.max(0,this.state.heroHp-result.damage)}this.log(actionSummary(result,defender.name));this.emit({type:'damage-applied',side,result});return result}
 async heroAction(action,presenter){const target=this.target();if(!target)return;const hero=this.state.hero;if(action.kind==='attack'){this.state.heroEnergy=Math.min(hero.maxEnergy,this.state.heroEnergy+10);return this.executeDamage(hero,target,{type:'physical',multiplier:1},presenter,'hero')}
  const cost=Math.max(0,Number(action.cost)||0);if(this.state.heroEnergy<cost){this.log('⚡ 能量不足！');return}this.state.heroEnergy-=cost;this.state.heroEnergy=Math.min(hero.maxEnergy,this.state.heroEnergy+Math.max(0,Number(action.energyGain)||0));this.log(`${action.icon||'✨'} ${hero.name}使用「${action.name}」！`);let last=null;for(const e of(action.effects||[])){if(e.type==='damage'){last=await this.executeDamage(hero,target,{type:e.damageType||'physical',damageType:e.damageType||'physical',source:e.source,multiplier:Number(e.multiplier)||1,defensePierce:Number(e.defensePierce||0)},presenter,'hero');if(!target.alive)break}else if(e.type==='status'){const self=action.actionType==='self'||e.target==='self',unit=self?hero:target,mods=modifiersToMap(e.modifiers||[]);addStatus(unit,{type:action.id,name:action.name,effectType:e.category||'buff',turns:Number(e.duration)||1,mods});this.log(`${action.icon||'✨'} ${unit.name}獲得「${action.name}」。`)}}return last}
 async enemyAction(unit,presenter){if(!unit?.alive||unit.hp<=0)return;const magic=unit.magicAttack>unit.attack*1.15,action={id:'basic_attack',name:'攻擊',type:magic?'arcane':'physical',multiplier:1,source:magic?'magicAttack':'attack'};this.log(`👹 ${unit.name}攻擊！`);return this.executeDamage(unit,this.state.hero,action,presenter,'enemy')}
 async playerAction(action,presenter){const s=this.state;if(!s||s.busy||s.ended)return false;if(action.kind==='skill'&&s.heroEnergy<(Number(action.cost)||0)){this.log('⚡ 能量不足！');return false}if(!this.target()){this.log('沒有可攻擊的目標。');return false}s.busy=true;s.round++;this.emit({type:'round-start',round:s.round});const queue=this.initiative();this.log(`⏱️ 行動順序：${queue.map(x=>`${x.side==='hero'?'🧒':'👹'}${x.unit.name}(${Math.round(effectiveBattleValue(x.unit,'speed'))})`).join(' → ')}`);for(const turn of queue){if(s.ended)break;if(turn.side==='hero'){const skip=this.statusTick(s.hero,true);if(!skip)await this.heroAction(action,presenter)}else{if(turn.unit.hp<=0||!turn.unit.alive)continue;const skip=this.statusTick(turn.unit,false);if(!skip)await this.enemyAction(turn.unit,presenter)}if(this.checkEnd())break;await sleep(BATTLE_CONFIG.delay)}s.busy=false;this.emit({type:'round-end',round:s.round});return true}
 checkEnd(){const s=this.state;if(s.heroHp>0&&s.enemies.some(x=>x.hp>0&&x.alive!==false)&&s.round<BATTLE_CONFIG.maxRounds)return false;s.ended=true;s.result=s.heroHp>0&&s.enemies.every(x=>x.hp<=0||x.alive===false)?'win':'lose';this.emit({type:'end',result:s.result});return true}
}
