import { getGame, update } from '../core/store.js';
import { assetUrl, applySceneLayout } from '../visual/scene-renderer.js';
import { heroSpritePath } from '../character/hero-service.js';
import { worldForDate } from '../world/world-service.js';
import { localDateString } from '../core/date.js';
import { monsterDef } from './monster-database.js';
import { availableBattleSkills } from './skill-service.js';
let overlay=null,engine=null,onClose=null;
function pct(v,m){return Math.max(0,Math.min(100,Math.round((Number(v)||0)/Math.max(1,Number(m)||1)*100)))}
function statusHTML(unit){return(unit?.statuses||[]).map(s=>`<span class="status-token">${s.name||s.type} ${s.turns}</span>`).join('')}
function enemySprite(monsterId,state='idle'){const def=monsterDef(monsterId);if(def.mirrorHero)return assetUrl(heroSpritePath(state==='battle'?'attack':'idle'));return assetUrl(`images/monsters/${monsterId}_${state}.png`)}
function background(){const w=worldForDate(),src=assetUrl(w?.background||'images/backgrounds/week01_grassland.png');return`<div class="scene-background"><div class="scene-background-track"><img src="${src}" alt=""><img src="${src}" alt=""></div></div>`}
function enemyActorsHTML(s){return s.enemies.filter(x=>x.alive!==false&&x.hp>0).map(x=>`<div class="scene-actor battle-actor enemy ${x.isSummon?'summon':''}" data-actor="enemy" data-enemy-uid="${x.uid}"><img src="${enemySprite(x.monsterId,'idle')}" alt="${x.name}"></div>`).join('')}
function renderEnemyActors(s){const layer=overlay?.querySelector('#bEnemyLayer');if(!layer)return;layer.innerHTML=enemyActorsHTML(s);requestAnimationFrame(()=>applySceneLayout(overlay))}
function renderState(s){if(!overlay||!s)return;const target=s.enemies.find(x=>x.uid===s.selectedEnemyUid)||s.enemies.find(x=>x.hp>0),hpH=pct(s.heroHp,s.hero.maxHp),hpE=pct(target?.hp,target?.maxHp),enH=pct(s.heroEnergy,s.hero.maxEnergy);overlay.querySelector('#bHeroHp').style.width=hpH+'%';overlay.querySelector('#bHeroHpText').textContent=`❤️ ${Math.round(s.heroHp)} / ${s.hero.maxHp}`;overlay.querySelector('#bHeroEnergy').style.width=enH+'%';overlay.querySelector('#bHeroEnergyText').textContent=`⚡ ${Math.round(s.heroEnergy)} / ${s.hero.maxEnergy}`;overlay.querySelector('#bEnemyHp').style.width=hpE+'%';overlay.querySelector('#bEnemyHpText').textContent=`❤️ ${Math.max(0,Math.round(target?.hp||0))} / ${target?.maxHp||0}`;overlay.querySelector('#bEnemyName').textContent=target?.name||'敵人';overlay.querySelector('#bHeroStatus').innerHTML=statusHTML(s.hero);overlay.querySelector('#bEnemyStatus').innerHTML=statusHTML(target);overlay.querySelector('#bRound').textContent=`ROUND ${s.round}`;overlay.querySelector('#bLog').innerHTML=s.logs.slice(-9).map(x=>`<div>${x}</div>`).join('');overlay.querySelector('#bTargetStrip').innerHTML=s.enemies.map(x=>`<button class="battle-target ${x.uid===s.selectedEnemyUid?'selected':''}" data-target="${x.uid}" ${x.hp<=0?'disabled':''}>${x.isSummon?'➕':x.isBoss?'👑':'👹'} ${x.name}<small>${Math.max(0,Math.round(x.hp))}/${x.maxHp}${x.mp!=null?`｜MP ${Math.round(x.mp)}`:''}</small></button>`).join('');renderEnemyActors(s);overlay.querySelectorAll('[data-battle-action],#bSkills').forEach(b=>b.disabled=s.busy||s.ended);if(s.ended){const r=overlay.querySelector('#bResult');r.innerHTML=`<div class="battle-result"><div class="battle-result-icon">${s.result==='win'?'🏆':'💀'}</div><h2>${s.result==='win'?'勝利！':'戰敗！'}</h2><div class="small">2.0 BattleEngine：1.0 核心公式 + 怪物技能／AI／召喚正式模組。</div><button id="bClose" class="action-button ${s.result==='win'?'primary':''}">返回副本</button></div>`;r.querySelector('#bClose').onclick=closeBattle}}
async function presenter(event,s){renderState(s);if(!overlay||event.type!=='attack')return;const actor=event.side==='hero'?overlay.querySelector('[data-battle-actor="hero"]'):overlay.querySelector(`[data-enemy-uid="${event.attackerUid}"]`),target=event.side==='hero'?overlay.querySelector(`[data-enemy-uid="${event.targetUid}"]`):overlay.querySelector('[data-battle-actor="hero"]');if(!actor||!target)return;if(event.side==='hero'){const img=actor.querySelector('img');img.src=assetUrl(heroSpritePath('attack'));await actor.animate([{transform:'translate(-50%,-100%)'},{transform:'translate(calc(-50% + 70px),-100%)',offset:.48},{transform:'translate(-50%,-100%)'}],{duration:420,easing:'ease-out'}).finished.catch(()=>{});img.src=assetUrl(heroSpritePath('idle'))}else{const img=actor.querySelector('img');img.src=enemySprite(event.monsterId||engine.monsterId,'battle');await actor.animate([{transform:'translate(-50%,-100%)'},{transform:'translate(calc(-50% - 55px),-100%)',offset:.48},{transform:'translate(-50%,-100%)'}],{duration:460,easing:'ease-out'}).finished.catch(()=>{});img.src=enemySprite(event.monsterId||engine.monsterId,'idle')}if(event.result?.damage>0)target.animate([{filter:'brightness(1)'},{filter:'brightness(2.2)'},{filter:'brightness(1)'}],{duration:220})}
function settle(result){if(result!=='win')return;update(()=>{const g=getGame(),h=g.hero;h.gold=(Number(h.gold)||0)+15;h.exp=(Number(h.exp)||0)+15;h.maxExp=Math.max(1,Number(h.maxExp)||100);while(h.exp>=h.maxExp){h.exp-=h.maxExp;h.level=(Number(h.level)||1)+1;h.maxExp=Math.floor(h.maxExp*1.2);for(const k of Object.keys(h.stats||{}))h.stats[k]=(Number(h.stats[k])||0)+1}g.battleRecords=g.battleRecords||[];g.battleRecords.push({id:`battle_${Date.now().toString(36)}`,date:localDateString(),enemyName:monsterDef(engine.monsterId).name,enemyPower:engine.enemyPower,result:'win',eventType:engine.eventType,rounds:engine.state.round,battleV2:true})})}
export async function openBattle(battleEngine,closeCallback){engine=battleEngine;onClose=closeCallback;const [skills]=await Promise.all([availableBattleSkills(),engine.prepare()]);const s=engine.start(),def=monsterDef(engine.monsterId);overlay=document.createElement('div');overlay.className='battle-overlay-v2';overlay.innerHTML=`<div class="battle-window-v2"><div class="battle-top-v2"><div class="battle-unit-v2"><b>${s.hero.name}</b><div class="hp-bar-v2"><i id="bHeroHp"></i></div><div id="bHeroHpText" class="bar-text"></div><div class="energy-bar-v2"><i id="bHeroEnergy"></i></div><div id="bHeroEnergyText" class="bar-text"></div><div id="bHeroStatus" class="battle-status-line"></div></div><div class="battle-unit-v2"><b id="bEnemyName">${def.name}</b><div class="hp-bar-v2"><i id="bEnemyHp"></i></div><div id="bEnemyHpText" class="bar-text"></div><div id="bEnemyStatus" class="battle-status-line"></div></div></div><div id="bTargetStrip" class="battle-target-strip"></div><div class="battle-arena-v2" data-scene="battle">${background()}<div id="bRound" class="battle-round">ROUND 0</div><div class="scene-actor battle-actor hero" data-actor="hero" data-battle-actor="hero"><img src="${assetUrl(heroSpritePath('idle'))}" alt="勇者"></div><div id="bEnemyLayer"></div></div><div id="bLog" class="battle-log-v2"></div><div class="battle-actions-v2"><button data-battle-action="attack" class="action-button red">⚔️ 攻擊<small>回復10能量</small></button><button id="bSkills" class="action-button purple">✨ 技能<small>最多4槽</small></button><button id="bCancel" class="action-button">關閉<small>不結算</small></button></div><div id="bSubmenu" class="battle-submenu-v2"></div><div id="bResult"></div></div>`;document.body.appendChild(overlay);engine.subscribe((state,event)=>{renderState(state);if(event.type==='end')settle(event.result)});renderState(s);requestAnimationFrame(()=>applySceneLayout(overlay));overlay.querySelector('[data-battle-action="attack"]').onclick=()=>engine.playerAction({kind:'attack',name:'攻擊'},presenter);overlay.querySelector('#bSkills').onclick=()=>{const box=overlay.querySelector('#bSubmenu');box.innerHTML=skills.map((sk,i)=>`<button class="battle-choice-v2" data-skill-index="${i}"><strong>${sk.icon||'✨'} ${sk.name}　⚡${Number(sk.cost)||0}</strong><span>${sk.description||''}</span></button>`).join('');box.classList.toggle('show');box.querySelectorAll('[data-skill-index]').forEach(b=>b.onclick=()=>{box.classList.remove('show');engine.playerAction({...skills[Number(b.dataset.skillIndex)],kind:'skill'},presenter)})};overlay.querySelector('#bTargetStrip').onclick=e=>{const b=e.target.closest('[data-target]');if(b)engine.selectTarget(b.dataset.target)};overlay.querySelector('#bCancel').onclick=closeBattle}
export function closeBattle(){overlay?.remove();overlay=null;engine=null;onClose?.();onClose=null}
