import { BATTLE_CONFIG, DAMAGE_TYPES, STATUS_DEFS } from './battle-config.js';
import { jobRuleFor, JOB_BATTLE_CONFIG } from '../character/job-rules.js';
export const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
export function effectiveStat(raw){raw=Math.max(0,Number(raw)||0);return BATTLE_CONFIG.statScale*(1-Math.exp(-raw/BATTLE_CONFIG.statScale))}
function rawHeroStat(hero,key){return key==='virtue'?Number(hero?.virtue)||0:Number(hero?.stats?.[key])||0}
function jobEffectiveCoreValue(hero,rule){const keys=rule.kind==='dual'?rule.cores:[rule.core],vals=keys.map(k=>effectiveStat(rawHeroStat(hero,k))),core=rule.kind==='dual'?Math.min(...vals):vals[0],second=effectiveStat(rawHeroStat(hero,rule.secondary)),t=JOB_BATTLE_CONFIG.combatCoreThreshold;return (core<=t?core:t+(core-t)*JOB_BATTLE_CONFIG.overThresholdEfficiency)+second*JOB_BATTLE_CONFIG.secondaryCompensation}
function passiveMods(hero){const p=hero?.jobPassive;return{attack:p==='warrior_grit'?1.06:p==='spellblade'?1.04:1,magic:p==='mana_echo'?1.06:p==='spellblade'?1.04:1,defense:p==='holy_guard'?1.07:p==='warrior_grit'?1.04:1,evade:p==='shadow_step'?.04:0,crit:p==='hunter_instinct'?.04:0,statusRes:p==='blessing'?.08:0}}
export function makeHeroBattleStats(hero){const s=hero?.stats||{},e={str:effectiveStat(s.str),int:effectiveStat(s.int),agi:effectiveStat(s.agi),will:effectiveStat(s.will),virtue:effectiveStat(hero?.virtue||0)},lv=Number(hero?.level)||1,pm=passiveMods(hero),rule=jobRuleFor(hero),core=rule?jobEffectiveCoreValue(hero,rule):0,mastery=rule?clamp((core-35)/250,0,.18):0,maxHp=Math.round(100+lv*10+e.will*3+e.str),maxEnergy=Math.round(50+e.int*.5+e.will*.3);return{side:'hero',name:hero?.name||'勇者',...e,maxHp,maxEnergy,attack:(10+e.str*1.25)*(1+mastery)*pm.attack,magicAttack:(8+e.int*1.25)*(1+mastery)*pm.magic,defense:(10+e.will*.8)*(1+mastery*.6)*pm.defense,magicDefense:(8+e.will*.75)*(1+mastery*.6)*pm.defense,speed:e.agi,crit:clamp(.05+.25*(e.agi/(e.agi+100))+pm.crit,.05,.35),evade:clamp(.02+.20*(e.agi/(e.agi+100))+pm.evade,.02,.30),parry:clamp(.03+.08*(e.will/(e.will+100)),.03,.11),block:clamp(.05+.14*(e.will/(e.will+100)),.05,.19),statusRes:clamp(.05+.25*(e.will/(e.will+100))+pm.statusRes,.05,.40),elementalBaseRes:clamp(.15*(e.will/(e.will+100)),0,.15),resist:{fire:0,ice:0,lightning:0,wind:0,poison:0,curse:0},statuses:[],guarding:false}}
export function deriveEnemyStats(power,def,eventType='daily'){const name=def?.name||'怪物',boss=eventType==='midterm'||eventType==='final',rawBase=Math.max(8,Number(power||70)/4.1),variance=label=>name.includes('史萊姆')?(label==='will'?.85:label==='agi'?.8:1):name.includes('哥布林')?(label==='agi'?1.25:label==='will'?.8:1):name.includes('獸人')?(label==='str'?1.3:label==='agi'?.8:1):name.includes('骷髏')?(label==='int'?1.25:label==='str'?.85:1):name.includes('騎士')?(label==='will'?1.3:label==='agi'?.8:1):1,e={str:effectiveStat(rawBase*variance('str')),int:effectiveStat(rawBase*.9*variance('int')),agi:effectiveStat(rawBase*.9*variance('agi')),will:effectiveStat(rawBase*variance('will')),virtue:0},maxHp=Math.round((boss?150:100)+(boss?5.2:3.6)*e.will+e.str),maxEnergy=Math.round(45+e.int*.45+e.will*.25),resist={fire:0,ice:0,lightning:0,wind:0,poison:0,curse:0};if(name.includes('史萊姆')){resist.fire=-.15;resist.ice=.10}if(name.includes('獸人')){resist.fire=.15;resist.ice=-.20}if(name.includes('骷髏')){resist.poison=.85;resist.curse=.25;resist.fire=-.10}if(name.includes('騎士')){resist.fire=.10;resist.ice=.10;resist.lightning=.10;resist.wind=.10}return{side:'enemy',name,...e,maxHp,maxEnergy,attack:9+e.str*1.15,magicAttack:7+e.int*1.15,defense:8+e.will*.75,magicDefense:7+e.will*.70,speed:e.agi,crit:clamp(.04+.20*(e.agi/(e.agi+100)),.04,.24),evade:clamp(.02+.16*(e.agi/(e.agi+100)),.02,.18),parry:clamp(.02+.07*(e.will/(e.will+100)),.02,.09),block:clamp(.04+.12*(e.will/(e.will+100)),.04,.16),statusRes:clamp(.04+.22*(e.will/(e.will+100)),.04,.26),elementalBaseRes:clamp(.12*(e.will/(e.will+100)),0,.12),resist,statuses:[],guarding:false,boss}}
export function effectMod(unit,key){return(unit?.statuses||[]).reduce((a,s)=>a+Number(s.mods?.[key]||0),0)}
export function effectiveBattleValue(unit,key){return Math.max(0,Number(unit?.[key]||0)+effectMod(unit,key))}
export function totalElementRes(defender,type){const special=Number(defender?.resist?.[type]||0),base=type==='poison'||type==='curse'?0:Number(defender?.elementalBaseRes||0);return clamp(base+special,-.50,.75)}
export function statusChance(base,defender,statusType){const special=Number(defender?.resist?.[statusType]||0);return clamp(Number(base||0)*(1-(Number(defender?.statusRes)||0))*(1-special),0,.95)}
export function addStatus(target,status){target.statuses=target.statuses||[];const existing=target.statuses.find(s=>s.type===status.type);if(existing){existing.turns=Math.max(existing.turns,status.turns);existing.power=Math.max(existing.power||0,status.power||0);existing.mods={...(existing.mods||{}),...(status.mods||{})};return existing}const next={...status};target.statuses.push(next);return next}
export function statusLabel(s){const d=STATUS_DEFS[s.type];return `${d?.icon||'🌀'} ${s.name||d?.name||s.type}`}
export function resolveAttack(attacker,defender,action={damageType:'physical',multiplier:1}){const damageType=action.damageType||action.type||'physical',physical=damageType==='physical',hit=clamp(BATTLE_CONFIG.baseHit+(attacker.speed-defender.speed)*.001+effectMod(attacker,'hit'),.45,.99);if(!action.forceHit&&Math.random()>hit)return{type:'miss',damage:0,damageType};if(!action.forceHit&&action.canDodge!==false&&Math.random()<effectiveBattleValue(defender,'evade'))return{type:'dodge',damage:0,damageType};if(!action.forceHit&&physical&&action.canParry!==false&&Math.random()<effectiveBattleValue(defender,'parry'))return{type:'parry',damage:0,damageType};const crit=action.forceCrit===true||Math.random()<effectiveBattleValue(attacker,'crit'),source=action.source||(physical?'attack':'magicAttack'),attack=effectiveBattleValue(attacker,source),defense=physical?effectiveBattleValue(defender,'defense'):effectiveBattleValue(defender,'magicDefense'),pierce=clamp(Number(action.defensePierce||0),0,.90);let raw=Math.max(1,attack*(action.multiplier||1)-defense*(1-pierce)*.50),weak=false,resisted=false;if(!physical&&DAMAGE_TYPES[damageType]?.elemental!==false){const res=totalElementRes(defender,damageType);raw*=1-res;weak=res<-.05;resisted=res>.10}const focus=attacker.statuses?.find(s=>Number(s.mods?.nextAttackMultiplier||0)>0);if(focus){raw*=1+Number(focus.mods.nextAttackMultiplier||0);focus.turns=0}raw*=.90+Math.random()*.20;raw*=Math.max(.10,1+effectMod(defender,'damageTaken'));let blocked=false;if(!action.forceHit&&physical&&action.canBlock!==false&&Math.random()<effectiveBattleValue(defender,'block')){raw*=BATTLE_CONFIG.blockReduction;blocked=true}if(crit)raw*=BATTLE_CONFIG.critDamage;if(action.mirrorDuel)raw=Math.max(raw,Math.max(2,Math.round(Number(defender.maxHp||1)*.02)));if(action.minDamage!=null)raw=Math.max(raw,Math.max(0,Number(action.minDamage)||0));return{type:blocked?'block':'hit',damage:Math.max(1,Math.round(raw)),damageType,crit,weak,resisted}}
