import { BATTLE_CONFIG } from './battle-config.js';
import { makeHeroBattleStats, deriveEnemyStats, resolveAttack, addStatus, effectiveBattleValue, statusLabel, statusChance } from './battle-math.js';
import { monsterDef } from './monster-database.js';
import { ensureContentDatabase } from '../data/content-provider.js';
import { monsterAI, monsterSkill, isMagicCaster, chooseEnemySkill, statusFromMonsterSkill, initiativeBonus } from './monster-ai.js';
import { MULTI_ENEMY_RULES, MIRROR_RULES, applyBattleStartMechanics, canUseSummonSkill, executeSummonSkill, afterEnemyDamaged, afterEnemyDefeated, beforeEnemyStatusTick, beforeEnemyTurn, executeTriggerSkill, enemyDamageMultiplier, afterEnemyDamageResolved, afterRound } from './monster-mechanics.js';
import { applyPhaseEntryModifiers } from './phase-service.js';
import { phaseCombatProfile } from './phase-database.js';
import { applyExamBreakToEnemy, initializeExamBattleState, absorbExamShield } from '../exam/exam-boss-service.js';
import {
  createFormalRuntime,initFormalResources,heroInitiativeBonus,formalInitiativeEntries,formalAllyTurn,
  formalSkillPreflight,executeFormalSkill,formalTurnStart,afterFormalStatusTick,afterHeroBasicAttack,afterEnemyDamageToHero,
  modifyHeroDamageResult,mitigateIncomingHeroDamage,preventHeroDeath,restoreFormalPrimaryResource,formalBasicAttackAction
} from './formal-class-runtime.js';

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function actionSummary(r,target){if(r.type==='miss')return'💨 攻擊落空！';if(r.type==='dodge')return`💨 ${target}閃避成功！`;if(r.type==='parry')return`⚔️ ${target}招架成功！`;if(r.type==='block')return`🛡️ ${target}格擋，只受到 ${r.damage} 點傷害。`;return`${r.crit?'💥 致命一擊！':''}${r.weak?' WEAK！':''}${r.resisted?' RESIST！':''}造成 ${r.damage} 點傷害。`}
function modifiersToMap(modifiers=[]){const out={};for(const m of modifiers){if(m?.operation==='add')out[m.target]=(out[m.target]||0)+Number(m.value||0)}return out}

export class BattleEngine{
 constructor({hero,monsterId,enemyPower,eventType='daily',campaignProgress={},phaseScopeKey='',equipmentStats={},examContext=null}={}){this.heroSource=hero;this.monsterId=monsterId;this.enemyPower=Number(enemyPower)||1;this.eventType=eventType;this.campaignProgress=campaignProgress||{};this.phaseScopeKey=String(phaseScopeKey||'');this.equipmentStats=equipmentStats||{};this.examContext=examContext||null;this.listeners=new Set();this.state=null;this.content=null}
 async prepare(){this.content=await ensureContentDatabase()||{};return this}
 subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn)}
 emit(event){for(const fn of this.listeners)fn(this.snapshot(),event)}
 snapshot(){return this.state?structuredClone(this.state):null}
 aiFor(id){return monsterAI(this.content,id)}
 skillFor(id){return monsterSkill(this.content,id)}
 livingEnemies(){return(this.state?.enemies||[]).filter(x=>x.alive!==false&&x.hp>0)}
 heroSkillMap(){const db=this.content||{},all=[...(db.beginner||[]),...Object.values(db.jobs||{}),...Object.values(db.formalClassSkills||{}).flat()];return new Map(all.filter(Boolean).map(s=>[s.id,s]))}
 mirrorSkillFor(unit){const ai=this.aiFor(unit.monsterId);if(!ai.copyHero)return null;if(ai.copyEquippedSkills){const map=this.heroSkillMap(),ids=(this.heroSource?.equippedSkills||[]).filter(id=>map.has(id));if(ids.length){const id=ids[Number(unit.mirrorSkillIndex||0)%ids.length];unit.mirrorSkillIndex=Number(unit.mirrorSkillIndex||0)+1;const source=map.get(id);if(source)return{...source,id:`mirror_${source.id}`,name:`鏡像・${source.name}`,kind:'mirror_copy',mirrorSourceId:source.id}}}return{id:'mirror_attack',name:'鏡像攻擊',kind:'physical',target:'single',multiplier:1,mirrorDuel:true,defensePierce:MIRROR_RULES.defensePierce}}
 makeEnemy(monsterId,opts={}){
  const def=monsterDef(monsterId),ai=this.aiFor(monsterId),mirror=!!(ai.copyHero||def.mirrorHero),base=mirror?makeHeroBattleStats(this.heroSource):deriveEnemyStats(this.enemyPower,def,this.eventType),defaultScale=mirror?Number(ai.statScale??1):1,scale=Number(opts.statScale??defaultScale),bossLike=!!(opts.isBoss??def.boss)||['midterm','final'].includes(this.eventType),caster=isMagicCaster(this.content,monsterId),phaseProfile=phaseCombatProfile(monsterId);
  let attackRoleScale=1,magicRoleScale=1;if(caster){magicRoleScale=bossLike?1.55:1.30;attackRoleScale=.90}if(Number.isFinite(Number(phaseProfile.magicRoleScale)))magicRoleScale=Math.max(magicRoleScale,Number(phaseProfile.magicRoleScale));if(monsterId==='necromancer')magicRoleScale=Math.max(magicRoleScale,1.35);
  const hpScale=Number(opts.hpScale??(mirror?MIRROR_RULES.hpScale:scale))*(def.finalBoss?1.35:1),unit={...base,uid:opts.uid||`${monsterId}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`,monsterId,name:opts.name||def.name,isBoss:!!(opts.isBoss??def.boss),isSummon:!!opts.isSummon,summonedBy:opts.summonedBy||null,maxHp:Math.max(1,Math.round(base.maxHp*hpScale)),hp:0,alive:true,attack:base.attack*scale*attackRoleScale,magicAttack:base.magicAttack*scale*magicRoleScale,defense:base.defense*scale,magicDefense:base.magicDefense*scale,speed:base.speed*scale,statuses:[],skillUses:{},cooldowns:{},chargedSkill:null,rotationIndex:0,turnsTaken:0,maxMp:Number(ai.maxMp||ai.mp||base.maxEnergy||50),mp:Number(ai.mp??ai.maxMp??base.maxEnergy??50)};
  unit.hp=unit.maxHp;Object.assign(unit,opts.flags||{});if(opts.forceBasicOnly)unit.forceBasicOnly=true;if(opts.soulLinked)unit.soulLinked=true;if(this.examContext)applyExamBreakToEnemy(unit,this.examContext);return unit;
 }
 start(){
  const hero=makeHeroBattleStats(this.heroSource),eq=this.equipmentStats||{};for(const k of ['attack','magicAttack','defense','magicDefense','speed','maxHp','maxEnergy'])hero[k]=Math.max(0,Number(hero[k]||0)+Number(eq[k]||0));hero.crit=Math.min(.60,Math.max(.05,Number(hero.crit||0)+Number(eq.crit||0)));hero.evade=Math.min(.50,Math.max(.02,Number(hero.evade||0)+Number(eq.evade||0)));hero.block=Math.min(.45,Math.max(.05,Number(hero.block||0)+Number(eq.block||0)));const enemy=this.makeEnemy(this.monsterId,{isBoss:['midterm','final'].includes(this.eventType)||monsterDef(this.monsterId).boss});
  const formal=createFormalRuntime(this.heroSource,hero);
  this.state={hero,enemies:[enemy],selectedEnemyUid:enemy.uid,round:0,busy:false,ended:false,result:'',heroHp:hero.maxHp,heroEnergy:Math.round(hero.maxEnergy*.50),formal,logs:['⚔️ 戰鬥開始！先鎖定目標再選擇行動。'],enemyPower:this.enemyPower,eventType:this.eventType,monsterId:this.monsterId,battleLoot:[]};
  initFormalResources(this.state);if(formal)this.state.logs.push(`🎓 ${formal.cls}正式職業 Runtime 已啟動。`);
  const phaseContext=applyPhaseEntryModifiers(enemy,{monsterId:this.monsterId,campaignProgress:this.campaignProgress,scopeKey:this.phaseScopeKey});if(phaseContext){this.state.phaseContext=phaseContext;if(phaseContext.message)this.state.logs.push(phaseContext.message)}
  if(this.examContext)initializeExamBattleState(this.state,this.examContext,msg=>this.state.logs.push(msg));applyBattleStartMechanics(this,enemy);this.emit({type:'start'});return this.snapshot();
 }
 target(){const alive=this.livingEnemies();let t=alive.find(x=>x.uid===this.state?.selectedEnemyUid)||alive[0]||null;if(t)this.state.selectedEnemyUid=t.uid;return t}
 log(message){if(!this.state)return;this.state.logs.push(message);if(this.state.logs.length>20)this.state.logs.shift();this.emit({type:'log',message})}
 selectTarget(uid){if(!this.state||this.state.busy||this.state.ended)return false;const t=this.livingEnemies().find(x=>x.uid===uid);if(!t)return false;this.state.selectedEnemyUid=uid;this.log(`🎯 鎖定目標：${t.name}`);return true}
 canUseSummonSkill(unit,skill){return canUseSummonSkill(this,unit,skill)}
 summonEnemy(monsterId,summoner,opts={}){if(this.livingEnemies().length>=MULTI_ENEMY_RULES.maxEnemies||this.livingEnemies().filter(x=>x.isSummon).length>=MULTI_ENEMY_RULES.maxSummons)return null;const unit=this.makeEnemy(monsterId,{isSummon:true,summonedBy:summoner?.uid||null,...opts});this.state.enemies.push(unit);this.emit({type:'summon',unitUid:unit.uid,monsterId:unit.monsterId});return unit}
 async present(presenter,event){this.emit(event);if(presenter)await presenter(event,this.snapshot())}
 statusTick(unit,isHero=false){
  let skip=false;const hadBleed=!isHero&&(unit.statuses||[]).some(s=>s.type==='bleed'&&s.turns>0);
  for(const st of [...(unit.statuses||[])]){let dmg=0;if(Number(st.maxHpDot)>0)dmg=Math.max(1,Math.round((isHero?this.state.hero.maxHp:unit.maxHp)*Number(st.maxHpDot)));else if(['poison','burn','bleed','holy_penance_dot'].includes(st.type))dmg=Math.max(1,Math.round(st.power||5));if(dmg){if(isHero)this.state.heroHp=Math.max(0,this.state.heroHp-dmg);else{unit.hp=Math.max(0,unit.hp-dmg);unit.alive=unit.hp>0;afterEnemyDamaged(this,unit);if(unit.hp<=0&&!unit.alive){this.log(`💀 ${unit.name}被擊倒。`);afterEnemyDefeated(this,unit);if(this.state.selectedEnemyUid===unit.uid)this.state.selectedEnemyUid=this.livingEnemies()[0]?.uid||null}}this.log(`${statusLabel(st)}：${unit.name}受到 ${dmg} 點傷害。`)}if(['stun','paralysis','freeze'].includes(st.type)&&st.guaranteedSkip!==false){skip=true;this.log(`${statusLabel(st)}！${unit.name}本回合無法行動。`)}st.turns--}
  unit.statuses=(unit.statuses||[]).filter(s=>s.turns>0);afterFormalStatusTick(this,unit,isHero,{hadBleed});return skip;
 }
 initiative(){
  const rows=[{side:'hero',unit:this.state.hero,order:0,initiativeScore:effectiveBattleValue(this.state.hero,'speed')+heroInitiativeBonus(this.state)},...formalInitiativeEntries(this.state),...this.livingEnemies().map((unit,i)=>({side:'enemy',unit,order:i+1,initiativeScore:effectiveBattleValue(unit,'speed')+initiativeBonus(this,unit)}))];
  return rows.sort((a,b)=>b.initiativeScore-a.initiativeScore||a.order-b.order);
 }
 applyDamageToEnemy(unit,damage){const dealt=Math.max(0,Math.round(damage));unit.hp=Math.max(0,unit.hp-dealt);unit.alive=unit.hp>0;afterEnemyDamaged(this,unit);if(unit.hp<=0&&!unit.alive){this.log(`💀 ${unit.name}被擊倒。`);afterEnemyDefeated(this,unit);if(this.state.selectedEnemyUid===unit.uid)this.state.selectedEnemyUid=this.livingEnemies()[0]?.uid||null}this.emit({type:'enemy-state',unitUid:unit.uid});return dealt}
 async executeDamage(attacker,defender,action,presenter,side){
  let result=resolveAttack(attacker,defender,action);if(side==='hero')result=modifyHeroDamageResult(this,result,action);else{result=mitigateIncomingHeroDamage(this,result,action);result=absorbExamShield(this.state,result,msg=>this.log(msg));}
  const attackerUid=side==='enemy'?attacker.uid:'hero',targetUid=side==='hero'?defender.uid:'hero';
  await this.present(presenter,{type:'attack',side,result,action,attackerName:attacker.name,attackerUid,targetName:defender.name,targetUid,monsterId:attacker.monsterId||null});
  if(result.damage){if(side==='hero')result.damage=this.applyDamageToEnemy(defender,result.damage);else{const before=this.state.heroHp;this.state.heroHp=Math.max(0,this.state.heroHp-result.damage);await afterEnemyDamageToHero(this,Math.max(0,before-this.state.heroHp),attacker,presenter);preventHeroDeath(this)}}
  this.log(actionSummary(result,defender.name));this.emit({type:'damage-applied',side,result,attackerUid,targetUid});return result;
 }
 async heroAction(action,presenter){
  const target=this.target();if(!target)return;const hero=this.state.hero;
  if(action.kind==='item'){const value=Math.max(0,Number(action.effectValue)||0);if(action.effectType==='heal_hp'){const before=this.state.heroHp;this.state.heroHp=Math.min(hero.maxHp,this.state.heroHp+value);this.log(`${action.icon||'🧪'} ${hero.name}使用「${action.name}」，恢復 ${Math.max(0,Math.round(this.state.heroHp-before))} HP。`)}else if(action.effectType==='heal_energy'){restoreFormalPrimaryResource(this.state,value);this.log(`${action.icon||'🧪'} ${hero.name}使用「${action.name}」，恢復職業資源。`)}else if(action.effectType==='poison'){const chance=statusChance(.75,target,'poison');if(Math.random()<chance){addStatus(target,{type:'poison',name:'中毒',turns:Math.max(1,Number(action.effectTurns)||3),power:value||6,effectType:'debuff',mods:{}});this.log(`☠️ ${target.name}中毒了。`)}else this.log(`🧪 ${target.name}抵抗了「${action.name}」。`)}else this.log(`${action.icon||'🧪'} 使用「${action.name}」。`);this.emit({type:'item-used',stackKey:action.stackKey,itemName:action.name});return{itemUsed:true}}
  if(action.kind==='attack'){const mirror=this.aiFor(target.monsterId).copyHero,live=mirror?{...formalBasicAttackAction(this.state),defensePierce:MIRROR_RULES.defensePierce,mirrorDuel:true}:formalBasicAttackAction(this.state);if(!this.state.formal)this.state.heroEnergy=Math.min(hero.maxEnergy,this.state.heroEnergy+10);const r=await this.executeDamage(hero,target,live,presenter,'hero');if(this.state.formal)await afterHeroBasicAttack(this,r,target,presenter);return r}
  if(action.formalClass&&this.state.formal)return executeFormalSkill(this,action,presenter);
  const cost=Math.max(0,Number(action.cost)||0);if(this.state.heroEnergy<cost){this.log('⚡ 能量不足！');return}this.state.heroEnergy-=cost;this.state.heroEnergy=Math.min(hero.maxEnergy,this.state.heroEnergy+Math.max(0,Number(action.energyGain)||0));this.log(`${action.icon||'✨'} ${hero.name}使用「${action.name}」！`);let last=null;
  for(const e of(action.effects||[])){if(e.type==='damage'){const live={type:e.damageType||'physical',damageType:e.damageType||'physical',source:e.source,multiplier:Number(e.multiplier)||1,defensePierce:Number(e.defensePierce||0)};if(this.aiFor(target.monsterId).copyHero){live.defensePierce=MIRROR_RULES.defensePierce;live.mirrorDuel=true}last=await this.executeDamage(hero,target,live,presenter,'hero');if(!target.alive)break}else if(e.type==='status'){const self=action.actionType==='self'||e.target==='self',unit=self?hero:target,mods=modifiersToMap(e.modifiers||[]);addStatus(unit,{type:action.id,name:action.name,effectType:e.category||'buff',turns:Number(e.duration)||1,mods});this.log(`${action.icon||'✨'} ${unit.name}獲得「${action.name}」。`)}}return last;
 }
 tryMonsterStatus(skill,target){const st=skill?.status;if(!st)return false;const chance=statusChance(Number(st.chance??1),target,st.id);if(Math.random()>chance)return false;const live=statusFromMonsterSkill(st,target);addStatus(target,live);this.log(`🌀 ${target.name}陷入「${live.name}」！`);return true}
 async executeMirrorSkill(unit,skill,presenter){let last=null;for(const e of skill.effects||[]){if(e.type==='damage'){const action={type:e.damageType||'physical',damageType:e.damageType||'physical',source:e.source||(e.damageType==='physical'?'attack':'magicAttack'),multiplier:Number(e.multiplier)||1,defensePierce:MIRROR_RULES.defensePierce,mirrorDuel:true};last=await this.executeDamage(unit,this.state.hero,action,presenter,'enemy');if(this.state.heroHp<=0)break}else if(e.type==='status'){const self=skill.actionType==='self'||e.target==='self'||e.category==='buff',target=self?unit:this.state.hero,mods=modifiersToMap(e.modifiers||[]);addStatus(target,{type:skill.mirrorSourceId||skill.id,name:skill.name,effectType:e.category||'buff',turns:Number(e.duration)||1,mods});this.log(`🪞 ${target.name}受到「${skill.name}」效果。`)}}return last}
 async executeEnemyDamage(unit,skill,presenter){const type=skill.kind==='magic'?(skill.element||'arcane'):'physical',hits=Number(skill.hits||0)||(skill.hitsMin?Math.floor(Math.random()*(Number(skill.hitsMax)-Number(skill.hitsMin)+1))+Number(skill.hitsMin):1),mechanicMultiplier=enemyDamageMultiplier(this,unit);let total=0;for(let i=0;i<hits;i++){const action={type,damageType:type,multiplier:Number(skill.multiplierPerHit||skill.multiplier||1)*mechanicMultiplier,source:skill.kind==='magic'?'magicAttack':'attack',defensePierce:Number(skill.defensePierce||0),mirrorDuel:!!skill.mirrorDuel,minDamage:unit.isSummon?Math.max(2,Math.round(this.state.hero.maxHp*.02)):undefined};const r=await this.executeDamage(unit,this.state.hero,action,presenter,'enemy');total+=Number(r.damage||0);if(this.state.heroHp<=0)break}if(total&&skill.status)this.tryMonsterStatus(skill,this.state.hero);if(skill.healFromDamage&&total){const heal=Math.round(total*Number(skill.healFromDamage));unit.hp=Math.min(unit.maxHp,unit.hp+heal);this.log(`🩸 ${unit.name}吸收生命，恢復 ${heal} HP。`)}afterEnemyDamageResolved(this,unit,skill);if(skill.selfMaxHpDamage){unit.hp=Math.max(1,unit.hp-Math.max(1,Math.round(unit.maxHp*Number(skill.selfMaxHpDamage))));this.log(`💢 ${unit.name}受到反噬。`)}if(skill.selfDestruct){unit.hp=0;unit.alive=false;afterEnemyDefeated(this,unit);this.log(`💥 ${unit.name}崩解。`)}return total}
 async enemyAction(unit,presenter){if(!unit?.alive||unit.hp<=0)return;const ai=this.aiFor(unit.monsterId);unit.turnsTaken++;for(const k of Object.keys(unit.cooldowns||{}))unit.cooldowns[k]=Math.max(0,Number(unit.cooldowns[k]||0)-1);if(this.state.round===1&&ai.alwaysActsFirstOnBattleStart&&!unit.firstStrikeAnnounced){unit.firstStrikeAnnounced=true;this.log(`🗡️ ${unit.name}速度壓制，第一回合搶先行動！`)}if(beforeEnemyTurn(this,unit))return;const skill=chooseEnemySkill(this,unit);if(!skill){this.log(`… ${unit.name}沒有可用行動。`);return}unit.skillUses[skill.id]=Number(unit.skillUses[skill.id]||0)+1;if(skill.cooldown)unit.cooldowns[skill.id]=Number(skill.cooldown);unit.lastSkillId=skill.id;this.log(`👹 ${unit.name}使用「${skill.name}」！`);if(skill.kind==='charge'){unit.chargedSkill=skill.nextSkill;this.log(`⚠️ ${unit.name}正在蓄力！下一次將使出「${this.skillFor(skill.nextSkill)?.name||skill.nextSkill}」。`);return}if(skill.requiresCharge)unit.chargedSkill=null;if(skill.kind==='trigger'){executeTriggerSkill(this,unit,skill);return}if(skill.kind==='mirror_copy'){await this.executeMirrorSkill(unit,skill,presenter);return}if(skill.kind==='heal'){let target=unit;if(skill.target==='ally_lowest_hp')target=this.livingEnemies().slice().sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0]||unit;const heal=Math.max(1,Math.round(target.maxHp*Number(skill.healMaxHp||0)));target.hp=Math.min(target.maxHp,target.hp+heal);this.log(`💚 ${target.name}恢復 ${heal} HP。`);this.emit({type:'enemy-state',unitUid:target.uid});return}if(['buff','shield'].includes(skill.kind)){const mods={};if(skill.damageTakenMultiplier!=null)mods.damageTaken=Number(skill.damageTakenMultiplier)-1;if(skill.atkMultiplier!=null)mods.attack=unit.attack*(Number(skill.atkMultiplier)-1);if(skill.evasionBonus!=null)mods.evade=Number(skill.evasionBonus);addStatus(unit,{type:skill.id,name:skill.name,effectType:'buff',turns:Number(skill.duration||2),mods});this.emit({type:'enemy-state',unitUid:unit.uid});return}if(skill.kind==='debuff'){this.tryMonsterStatus(skill,this.state.hero);return}if(skill.kind==='summon'){if(!executeSummonSkill(this,unit,skill))this.log(`📣 ${unit.name}召喚失敗。`);return}await this.executeEnemyDamage(unit,skill,presenter)}
 async playerAction(action,presenter){
  const s=this.state;if(!s||s.busy||s.ended)return false;
  if(action.kind==='skill'){if(action.formalClass&&s.formal){const pre=formalSkillPreflight(s,action);if(!pre.ok){this.log(pre.message);return false}}else if(s.heroEnergy<(Number(action.cost)||0)){this.log('⚡ 能量不足！');return false}}
  if(!this.target()){this.log('沒有可攻擊的目標。');return false}
  s.busy=true;s.round++;this.emit({type:'round-start',round:s.round});const queue=this.initiative();this.log(`⏱️ 行動順序：${queue.map(x=>`${x.side==='hero'?'🧒':x.side==='ally'?'🐕':'👹'}${x.unit.name}(${Math.round(Number(x.initiativeScore)||0)})`).join(' → ')}`);
  for(const turn of queue){
    if(s.ended)break;
    if(turn.side==='hero'){const skip=this.statusTick(s.hero,true);if(!skip){const pre=await formalTurnStart(this,presenter);if(!pre?.consumeAction)await this.heroAction(action,presenter)}}
    else if(turn.side==='ally'){await formalAllyTurn(this,turn.unit,presenter)}
    else{if(turn.unit.hp<=0||!turn.unit.alive)continue;beforeEnemyStatusTick(this,turn.unit);if(turn.unit.hp<=0||!turn.unit.alive)continue;const skip=this.statusTick(turn.unit,false);if(!skip)await this.enemyAction(turn.unit,presenter)}
    if(this.checkEnd())break;await sleep(BATTLE_CONFIG.delay)
  }
  afterRound(this);if(!s.ended)this.checkEnd();s.busy=false;this.emit({type:'round-end',round:s.round});return true;
 }
 checkEnd(){const s=this.state;if(s.heroHp<=0&&preventHeroDeath(this))return false;if(s.heroHp>0&&this.livingEnemies().length&&s.round<BATTLE_CONFIG.maxRounds)return false;s.ended=true;s.result=s.heroHp>0&&this.livingEnemies().length===0?'win':'lose';this.emit({type:'end',result:s.result});return true}
}
